<?php
/*------------------------------------------------------------------------
 # SM Mega Menu - Version 1.1
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php if($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::HORIZONTAL): ?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('sm/megamenu/css/horizontal/black/megamenu.css');?>" type="text/css" media="all">
<?php echo $this->getLayout()->getBlock('head')->addCss('sm/megamenu/css/horizontal/black/megamenu.css'); ?>

<?php elseif($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::VERTICAL):	?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('sm/megamenu/css/vertical/black/megamenu.css');?>" type="text/css" media="all">
<?php echo $this->getLayout()->getBlock('head')->addCss('sm/megamenu/css/vertical/black/megamenu.css'); ?>
<?php endif	?>
