<?php
/*------------------------------------------------------------------------
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

global $var_yttheme;  
// Include cpanel
if( $var_yttheme->getParam('showCpanel') ) { ?>
<div id="cpanel_wrapper" style="direction: ltr">
	<div class="cpanel-head">
		<span>Template Settings</span>
		<div class="action cpanel-reset">
			<a class="btn btn-info reset" href="#" onclick="javascript: onCPResetDefault(TMPL_COOKIE);">Reset</a>
		</div>		
	</div>

	<div class="accordion" id="ytcpanel_accordion">
		<!--Theme-->
        <div class="accordion-group cpanel-theme cpanel-theme-color">
            <div class="accordion-heading">
                <a class="accordion-toggle"  data-parent="#ytcpanel_accordion" href="#ytitem_1">
					<!--i class="icon-expand-alt"></i-->
					Theme Color
				</a>
            </div>
        	<div id="ytitem_1" class="accordion-theme">
                <div class="accordion-inner clearfix">
					<div class="color-theme">
                    	<span title="Pink" class="theme-color pink<?php echo ($var_yttheme->getParam('sitestyle')=='pink')?' active':'';?>">Pink</span>
						<span title="Emerald" class="theme-color emerald<?php echo ($var_yttheme->getParam('sitestyle')=='emerald')?' active':'';?>">Emerald</span>
						<span title="Orange" class="theme-color orange<?php echo ($var_yttheme->getParam('sitestyle')=='orange')?' active':'';?>">Orange</span>						
						<span title="Violet" class="theme-color violet<?php echo ($var_yttheme->getParam('sitestyle')=='violet')?' active':'';?>">Violet</span>						
					</div>
				</div>
			</div>
        </div>				

		<!-- Menu -->
		<div class="accordion-group cpanel-menu">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion" href="#ytitem_6">
				<!--i class="icon-expand-alt"></i-->
				Menu style </a>
			</div>
			<div id="ytitem_6" class="accordion-body">
				<div class="accordion-inner clearfix">
					<!-- Styles -->
					<div class="cp-item footer-background-color">
						<!--span>Styles</span-->
						<div class="inner">
							<select onchange="javascript: onCPApply();" name="ytcpanel_menustyle" class="cp_select">
								<option value="mega" <?php echo ($var_yttheme->getParam('menustyle')=='mega')?' selected="selected"':'';?>>Mega</option>
								<option value="css" <?php echo ($var_yttheme->getParam('menustyle')=='css')?' selected="selected"':'';?>>Css</option>
							</select>
						</div>
					</div>
				</div>
			</div>
		</div>		
	</div>
	<div id="cpanel_btn" class="normal">
		<i class="icon-hand-left"></i>
	</div>
</div>

<script type="text/javascript">
	// <![CDATA[
    jQuery(document).ready(function($){
        /* Begin: Enabling miniColors */
		/*$('.body-background-color .color-picker').miniColors({			
			change: function(hex, rgb) {
				$('body#bd').css('background-color', hex); 
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		$('.link-color .color-picker').miniColors({
			change: function(hex, rgb) {
				$('body a').css('color', hex);
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		$('.text-color .color-picker').miniColors({
			change: function(hex, rgb) {
				$('#yt_wrapper .page-title:before').css('background-color', hex);
				$('body').css('color', hex);
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		$('.header-background-color .color-picker').miniColors({
			change: function(hex, rgb) {
				$('#bg_menu').css('background-color', hex);
				$('.yt-header').css('background-color', hex);
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		$('.footer-background-color .color-picker').miniColors({
			change: function(hex, rgb) {
				$('#yt_footer').css('background-color', hex);
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});	*/	
		/*
		/* End: Enabling miniColors */
		/* Begin: Set click pattern */
		/*function patternClick(el, paramCookie, assign){
			$(el).click(function(){
				oldvalue = $(this).parent().find('.active').html();
				$(el).removeClass('active');
				$(this).addClass('active');
				value = $(this).html();
				if(assign.length > 0){
					for($i=0; $i < assign.length; $i++){
						$(assign[$i]).removeClass(oldvalue);
						$(assign[$i]).addClass(value);
					}
				}
				if(paramCookie){
					$('input[name$="ytcpanel_'+paramCookie+'"]').attr('value', value);
					createCookie(TMPL_NAME+'_'+paramCookie, value, 365);
				}
			});
		}
		/* Set click pattern */
		/*patternClick('.header-background-image .pattern', 'header-bgimage', Array('#yt_header', ''));
        patternClick('.body-background-image .pattern',   'body-bgimage',   Array('#bd', ''));
        patternClick('.footer-background-image .pattern', 'footer-bgimage', Array('#yt_footer', ''));*/
        /* End: Set click pattern */
		function templateSetting(array){
			if(array['0']){
				$('.body-background-color input.miniColors').attr('value', array['0']);
				$('.body-background-color a.miniColors-trigger').css('background-color', array['0']);
				$('input.ytcpanel_bgcolor').attr('value', array['0']);
			}
			if(array['1']){
				$('.link-color input.miniColors').attr('value', array['1']);
				$('.link-color a.miniColors-trigger').css('background-color', array['1']);
				$('input.ytcpanel_linkcolor').attr('value', array['1']);
			}
			if(array['2']){
				$('.text-color input.miniColors').attr('value', array['2']);
				$('.text-color a.miniColors-trigger').css('background-color', array['2']);
				$('input.ytcpanel_textcolor').attr('value', array['2']);
			}			
		}
		
		var array 			= Array('bgcolor','linkcolor','textcolor');
		var array_pink 		= Array('#FFFFFF','#666666','#666666');
		var array_orange		= Array('#FFFFFF','#666666','#666666');				
		var array_emerald   	= Array('#FFFFFF','#666666','#666666');
		var array_violet   	= Array('#FFFFFF','#666666','#666666');

		$('.theme-color.pink').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_pink);
			onCPApply();
		});
		$('.theme-color.orange').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_orange);
			onCPApply();
		});
		$('.theme-color.emerald').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_emerald);
			onCPApply();
		});		
		$('.theme-color.violet').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_violet);
			onCPApply();
		});		
    });
	// ]]>
    </script>
<?php } ?>

<?php
if(!defined('ACCORDION_SNYDERPLACE')){
    define('ACCORDION_SNYDERPLACE', 1);
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.cookie.min.js') ?>"></script>
<?php } ?>
