<?php
/*------------------------------------------------------------------------
 # SM Slider - Version 2.1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$list = $this->_getProducts();
if(!empty($list)){ 
	$import_str = "";
	$jsHelper = Mage::helper('core/js');
		// jquery has not added yet
	if (!defined('MAGENTECH_JQUERY')  && (int)$this->_getConfig('include_jquery')){
		// if module allowed jquery.
		$import_str .= $jsHelper->includeSkinScript('sm/slider/js/jquery-1.8.2.min.js');
		$import_str .= $jsHelper->includeSkinScript('sm/slider/js/jquery-noconflict.js');
		define('MAGENTECH_JQUERY',1);
	}
	//if (!defined('MAGENTECH_JQUERY_SLIDER')) {
		$import_str .= $jsHelper->includeSkinScript('sm/slider/js/slider.js');
		//define('MAGENTECH_JQUERY_SLIDER',1);
	//}
	echo $import_str;

	$tag_id = 'sm_slider_'.rand().time();
	$helper = Mage::helper('slider/data');
	$stop = (int)$this->_getConfig('stop',1) ? 'hover' : '';
	$play = (int)$this->_getConfig('play',1);
	$interval = (int)$this->_getConfig('delay');
	$interval = $play ? $interval : 0;
	$speed =(int)$this->_getConfig('duration');
	$start = (int) $this->_getConfig('start');
	$start = ( $start <= 0 || $start > count($list) ) ? 0 : $start - 1;
	$step = (int)$this->_getConfig('scroll',1);
	$step = $step <= 0 ? 1: $step;
?>
	<?php if($this->_getConfig('pretext') != '') { ?>
		<div class="pre-text"><?php echo $this->_getConfig('pretext'); ?></div>
	<?php } ?>
	<div id="<?php echo $tag_id; ?>" class="category-products sm-slider sm-slider-preload" style="<?php if( $this->_getConfig('anchor') == "bottom" ){
		echo "margin-bottom:40px;" ; } ?>">
			<div class="sm-slider-loading"></div>
			<div class="page-title-slider"><?php echo $this->_getConfig('slider_title_text') ; ?></div>
			<?php if($this->_getConfig('anchor') =="top"){?>
			<?php if($this->_getConfig('button_display') == 1){?>
			<div class="page-button <?php echo $this->_getConfig('anchor');?> <?php echo $this->_getConfig('control');?>">
				<ul class="control-button">
					<li class="preview">Prev</li>
					<li class="next">Next</li>
				</ul>		
			</div>
			<?php }}?>
		<?php $class_respl = 'preset01-' . $this->_getConfig('nb_column1', 4) . ' preset02-' . $this->_getConfig('nb_column2', 3) . ' preset03-' . $this->_getConfig('nb_column3', 2) . ' preset04-' . $this->_getConfig('nb_column4', 2) . ' preset05-' . $this->_getConfig('nb_column5', 1); ?>
		<div class="products-grid slider not-js cols-6 <?php echo $class_respl; ?>">
			<div class="vpo-wrap">
				<div class="vp">
					<div class="vpi-wrap">
					<?php foreach($list as $_product){
					?>
                    <?php 
					$now = date("Y-m-d H:m:s");
					$newsFrom= $_product->getNewsFromDate();
					$newsTo=  $_product->getNewsToDate();
					//$newsFrom= substr($_product->getData('news_from_date'),0,10);
					//$newsTo=  substr($_product->getData('news_to_date'),0,10);
					$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
					$price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
					//$saleoff= round(($price - $specialprice)/$price*100) ;
					$special_from_date = $_product->getSpecialFromDate();
					$special_to_date = $_product->getSpecialToDate();
					?>
						<div class="item">
							<div class="item-inner">
						
                            <div class="product-image">
                                <!--<a href="<?php //echo $_product->getProductUrl();?>" title="<?php //echo $_product->title; ?>" <?php //echo $helper->parseTarget($this->_getConfig('product_links_target'));?> >
                                    <img src="<?php //echo $_product->_image ;?>" alt="<?php //echo $_product->title; ?>" title="<?php //echo  $_product->title; ?>" />
                                </a>-->
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                <?php 														
								   if($_product->getThumbnail() != $_product->getSmallImage()) { ?> 
	                                   <img class="small-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($this->_getConfig('imgcfg_width'),$this->_getConfig('imgcfg_height')); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
	                                   <img class="thumnail-image image-hover" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($this->_getConfig('imgcfg_width'),$this->_getConfig('imgcfg_height')); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />                         	<?php } else { ?>
	                                    <img class="small-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($this->_getConfig('imgcfg_width'),$this->_getConfig('imgcfg_height')); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
	                               <?php } ?>
	                            </a>
                                <?php if ( $now>=$newsFrom && $now<=$newsTo ){ ?>
                                    <span class="new-product have-ico"><?php echo $this->__('New'); ?></span>
                                <?php }
                                if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){ ?>
                                    <span class="sale-product have-ico"><?php echo $this->__('Sale');?></span>
                                <?php } ?>
                                <div class="product-addto-wrap">
                                    <?php if ((int)$this->_getConfig('product_addcart_display', 1)) { ?>
										<?php if($_product->isSaleable()): ?>
                                        <a class="btn-cart product-addcart btn-addto" title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                            <?php echo $this->__('Add to Cart') ?>
                                        </a>
                                        <?php else: ?>
                                        <p class="availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?> </span>
                                        </p>
                                        <?php endif; ?>																
                                    <?php } ?>
                                    <?php if ($this->helper('wishlist')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1)) : ?>
                                    <a class="link-wishlist product-wishlist btn-addto" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>">
                                        <?php echo $this->__('Add to Wishlist') ?>
                                    </a>
                                    <?php endif; ?>
                                    
                                    <?php if($this->getAddToCompareUrl($_product) && (int)$this->_getConfig('product_addcompare_display', 1)): 							
									?>							
                                        <a class="product-compare btn-addto" href="<?php echo $this->getAddToCompareUrl($_product); ?>" title="<?php echo $this->__('Add to Compare'); ?>">
                                            <?php echo $this->__('Add to Compare') ?>
                                        </a>							
                                    <?php endif;?>
                                </div>
                            </div>
                            
                            <div class="product-info">
                                <div class="inner">
                                    <div class="product-info-left">
                                    <?php if( (int)$this->_getConfig('product_title_display',1) ){?>
                                        <div class="product-name">
                                            <a href="<?php echo $_product->getProductUrl();?>" title="<?php echo $_product->title; ?>" <?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?> >
                                                <?php echo $helper->truncate($_product->title,$this->_getConfig('product_title_maxlength'));?>
                                            </a>
                                        </div>
                                    <?php } ?>
                                    <?php if($this->_getConfig('product_source') != 'media' && (int)$this->_getConfig('product_reviews_count',1) && $_product->num_rating_summary != null){ ?>
                                        <div class="product-review">
                                            <?php  echo $this->getReviewsSummaryHtml($_product, "short", true); ?>
                                        </div>
                                     <?php } ?>
                                </div>
                                    <div class="product-price">
                                    <?php 
									 echo $this->getPriceHtml($_product,true);
									?>
                                </div>
                                </div>							
                            </div>
                            
                            <?php if((int)$this->_getConfig('product_description_display',1) && $helper->_trimEncode($_product->_description) != '' ){?>
                                <div class="item-des">
                                    <?php echo $_product->_description; ?>
                                </div>
                            <?php } 
                            if( (int)$this->_getConfig('product_readmore_display',1) ){?>
                            <div class="item-details">
                                <a href="<?php echo $_product->link;?>" <?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?> >
                                    <?php echo $this->_getConfig('product_readmore_text'); ?>
                                </a>
                            </div>	
                            <?php }?>
                        </div>
						</div>
					<?php }?>
					</div>
				</div>
			</div>
		</div>
		
		<?php if($this->_getConfig('anchor') !="top"){?>
			<?php if( (int)$this->_getConfig('button_display',1)){?>
			<div class="page-button <?php echo $this->_getConfig('anchor');?> <?php echo $this->_getConfig('control') ;?>">
				<ul class="control-button">
					<li class="preview">Prev</li>
					<li class="next">Next</li>
				</ul>		
			</div>
		<?php }}?>
		
	</div>
	<?php if( $this->_getConfig('posttext') != '' ) {  ?>
		<div class="post-text"><?php echo $this->_getConfig('posttext'); ?></div>
	<?php } ?>
	
	<script type="text/javascript">
	//<![CDATA[
		jQuery(document).ready(function($){
		;(function(element){
			var $el = $(element);
			function runSlider(){
				$('.slider',$el).responsiver({
					interval: <?php echo $interval; ?>,
					speed: <?php echo $speed; ?>,
					start: <?php echo $start; ?>,
					step: <?php echo $step; ?>,
					circular: true,
					preload: true,
					fx: 'fade',
					pause: '<?php echo $stop;?>',
					control:{
						prev: '#<?php echo $tag_id;?> .control-button li[class="preview"]',
						next: '#<?php echo $tag_id;?> .control-button li[class="next"]'
					},
					getColumns: function(_element){
						var match = $(_element).attr('class').match(/cols-(\d+)/);
						if (match[1]){
							var column = parseInt(match[1]);
						} else {
							var column = 1;
						}
						if (!column) column = 1;
						return column;
					}          
				});	
			}
			var _timer;
			$(window).load(function(){
				if(_timer) clearTimeout(_timer);
				_timer = setTimeout(function(){
					$el.removeClass('sm-slider-preload');
					$('.sm-slider-loading',$el).remove();
					runSlider();
				},500);
			});
		})('#<?php echo $tag_id;?>')
			
		});
	//]]>
	</script>  	
	
<?php
} else {
	echo $this->__('Has no item to show!');
}?>
 