<?php
/*------------------------------------------------------------------------
 # SM Image Slider - Version 1.1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getProducts();
if (!empty($list)) {
	$import_str = "";
	$jsHelper = Mage::helper('core/js');
	// jquery has not added yet
	if (!defined('MAGENTECH_JQUERY') && (int)$this->_getConfig('include_jquery')) {
		// if module allowed jquery.
		$import_str .= $jsHelper->includeSkinScript('sm/imageslider/js/jquery-1.9.1.min.js');
		$import_str .= $jsHelper->includeSkinScript('sm/imageslider/js/jquery-noconflict.js');
		define('MAGENTECH_JQUERY', 1);
	}
	if (!defined('MAGENTECH_JQUERY_SLIDER')) {
		$import_str .= $jsHelper->includeSkinScript('sm/imageslider/js/owl.carousel.js');
		define('MAGENTECH_JQUERY_SLIDER', 1);
	}
	echo $import_str;

	$tag_id = 'sm_imageslider_' . rand() . time();
	$helper = Mage::helper('imageslider/data');

	$stop = (int)$this->_getConfig('stop', 1) ? 'true' : 'false';
	$play = (int)$this->_getConfig('play', 1) ? 'true' : 'false';
	$step = (int)$this->_getConfig('scroll', 1);
	$step = $step <= 0 ? 1 : $step;
	$speed = (int)$this->_getConfig('duration');
	$interval = (int)$this->_getConfig('delay');
	$start = (int)$this->_getConfig('start');
	$start = ($start <= 0 || $start > count($list)) ? 0 : $start - 1;

	$nav = ($this->_getConfig('nav', 1) == 1) ? 'true' : 'false';
	$_navSpeed = $this->_getConfig('navSpeed', 1000);
	$navSpeed = (is_numeric($_navSpeed) && $_navSpeed >= 0) ? $_navSpeed : 1000;
	$loop = ($this->_getConfig('loop', 1) == 1) ? 'true' : 'false';
	$dots = ($this->_getConfig('dots', 1) == 1) ? 'true' : 'false';
	$_dotSpeed = $this->_getConfig('dotsSpeed');
	$dotsSpeed = (is_numeric($_dotSpeed) && $_dotSpeed >= 0) ? $_dotSpeed : 1000;
	$merge = ($this->_getConfig('merge', 1) == 1) ? 'true' : 'false';
	$_margin = $this->_getConfig('margin', 1);
	$margin = (is_numeric($_margin) && $_margin >= 0) ? $_margin : 5;
	$theme = $this->_getConfig('theme_display', 1);
	$mouseDrag = ($this->_getConfig('mouseDrag', 1) == 1) ? 'true' : 'false';
	$autoHeight = ($this->_getConfig('autoHeight', 1) == 1) ? 'true' : 'false';

	$_device1 = $this->_getConfig('nb_column1', 4);
	if ($theme == 'theme1') {
		$device1 = $_device1;
	} else {
		if($merge == 'true'){
			if ($_device1 == 1) {
				$device1 = 1;
			} else {
				$device1 = $_device1 + 1;
			}
		}else{
			$device1 = $_device1;
		}
	}
	$device2 = $this->_getConfig('nb_column2', 3);
		$_wide_box = $this->_getConfig('wide_box','wide');
		$wide_box = ($_wide_box == 'boxed')?' boxed':'';
	?>

	<?php if ($this->_getConfig('slider_title_text')) { ?>
		<div class="title-imageslider">
			<?php echo $this->_getConfig('slider_title_text'); ?>
		</div>
	<?php } ?>

	<?php if ($this->_getConfig('pretext') != '') { ?>
		<div class="image-pre-text"><?php echo $this->_getConfig('pretext'); ?></div>
	<?php } ?>

	<div id="<?php echo $tag_id; ?>" class="sm-imageslider imgsl-preload <?php echo $theme.$wide_box; ?>">
		<div class="sm-imageslider-loading"></div>
		<div  class="sm-imageslider-inner <?php echo $theme; ?>">

			<div class="sm-imageslider-content">
				<?php foreach ($list as $key => $_product) {

					if ($theme == 'theme1' ) {
						$data = 1;
					} else {
						if($merge == 'true'){
							if ($key % $_device1 == 0) {
								$data = 2;
							} else {
								$data = 1;
							}
						}else{
							$data = 1;
						}
					}

					?>
					<div class="item" data-merge="<?php echo $data; ?>">
						<div class="item-image">
							<a href="<?php echo $_product->link; ?>"
							   title="<?php echo $_product->title; ?>"
								<?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?> >
								<img src="<?php echo $_product->_image; ?>" alt="<?php echo $_product->title; ?>"/>
							</a>
						</div>
						<?php if ($theme == 'theme2' && ($this->_getConfig('product_description_display', 1) || $this->_getConfig('product_title_display', 1))) { ?>
							<div class="item-info">
								<?php if ($this->_getConfig('product_description_display', 1)) { ?>

									<div class="item-desc">
										<div class="item-desc-inner">
											<?php echo $_product->_description; ?>
										</div>
									</div>
								<?php } ?>

								<?php if ($this->_getConfig('product_title_display', 1)) { ?>
									<div class="item-title">
										<div class="item-title-inner">
											<a href="<?php echo $_product->link; ?>"
											   title="<?php echo $_product->title; ?>">
												<?php echo $_product->title; ?>
											</a>
										</div>
									</div>
								<?php } ?>

							</div>
						<?php } ?>
					</div>
				<?php } ?>
			</div>


		</div>
	</div>

	<?php if ($this->_getConfig('posttext') != '') { ?>
		<div class="image-post-text"><?php echo $this->_getConfig('posttext'); ?></div>
	<?php } ?>

	<script type="text/javascript">
		//<![CDATA[
		jQuery(document).ready(function ($) {
			;
			(function (element) {
				var $element = $(element),
					$sm_imageslider = $('.sm-imageslider-content', $element);

				$(window).on('load', function () {
					setTimeout(function () {
						$('.sm-imageslider-loading', $element).remove();
						$element.removeClass('imgsl-preload');
					__runImageSlider();

					}, 1000);

				});

				function __runImageSlider() {
					$sm_imageslider.on('initialized.owl.carousel', function () {
						<?php if($theme == 'theme2') { ?>
						$('.owl-nav', $element).insertBefore($('.owl-stage', $element));
						<?php } ?>


					});

					$sm_imageslider.owlCarousel({
						center: false,
						nav: <?php echo $nav;?>,
						loop: <?php echo $loop;?>,
						dots: <?php echo $dots;?>,
						dotsSpeed: <?php echo $dotsSpeed;?>,
						merge:<?php echo $merge;?>,
						margin: <?php echo $margin;?>,
						navText: ['&#139;', '&#155;'],
						slideBy: <?php echo $step;?>,
						autoplay: <?php echo $play;?>,
						autoplayTimeout: <?php echo $interval;?>,
						autoplayHoverPause: <?php echo $stop;?>,
						autoplaySpeed: <?php echo $speed;?>,
						startPosition: <?php echo $start;?>,
						navSpeed: <?php echo $navSpeed;?>,
						mouseDrag: <?php echo $mouseDrag;?>,
						responsive: {
							0: {
								items:<?php echo $device2;?>
							},
							768: {
								items:<?php echo $device1;?>
							}
						},
						autoHeight: <?php echo $autoHeight;?>
					});
				}

				function getHeightImage(){
					<?php if($theme == 'theme2') { ?>
					var _image = $('.item-image img' , $element);
					if(_image.length <= 0)
						_image = $('.item-image', $element);
					var _max_item = null;
					if(_image.length) {
						var hf = 0;
						_image.each(function(){
							var h = $(this).height();
							if(h > hf){
								hf = h;
								_max_item = $(this);
							}
						});
						 $('.item-image img', $element).height(_max_item.height());
					}
					<?php } ?>
				}
				$sm_imageslider.on('resized.owl.carousel refreshed.owl.carousel', function(){
					var _image = $('.item-image img' , $element);
					if(_image.length) {
						_image.each(function(){
							$(this).removeAttr('style');
						});
					}
					getHeightImage();
				});
			})('#<?php echo $tag_id; ?>');
		});
		//]]>
	</script>

<?php } else {
	echo $this->__('Has no item to show!');
} ?>
